name: optigas
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - openpyxl
  - streamlit
  - ipykernel
  - jupyterlab
  - sqlite
  - pip
  - plotly
  - pip:
      - sqlalchemy
